server:
  port: 5000
spring:
  application:
    name: zuul
  profiles:
    active: dev
file-service:
  fileter-pattern: /(pda)/[0-9]+
  fileter-app-pattern: /(pda)/[0-9]+\.\w+
  replace-url: /fileupload/fileupload/file/downFile/
auth:
  openUrls:
    - (.*)/login(.*)
zuul:
  host:
    # 设置超时时间
    connect-timeout-millis: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 设置超时时间
            timeoutInMilliseconds: 6000