zuul:
  routes:
    #标识你服务的名字，这里可以自己定义，一般方便和规范来讲还是跟自己服务的名字一样
    pda-service: /pda-service/**
eureka:
  #客户端
  client:
    #注册中心地址
    service-url:
      defaultZone: http://203.195.136.168:3000/eureka
  instance:
    instance-id: zuul
    prefer-ip-address: true
    ip-address: 203.195.136.168
